### ISSUE TITLE
message never acknowledged

### ISSUE THREAD

**Issue by arnaudlemaignen** [eht16/pylogbeat#1]
Hi
I am trying to use your project for doing some simulation of logs sent to logstash.
However I am never getting the ackownledge so the message is never sent.

DEBUG:pylogbeat:Sent window size: 2
DEBUG:pylogbeat:Sent payload bytes: 264, waiting for ACK: 2
DEBUG:pylogbeat:Received ACK: 0
DEBUG:pylogbeat:Received ACK: 0
DEBUG:pylogbeat:Received ACK: 0
DEBUG:pylogbeat:Received ACK: 0
DEBUG:pylogbeat:Received ACK: 0
DEBUG:pylogbeat:Received ACK: 0

Do you have a clue?
my logstash version is 5.6.10

I used your example as a bootstrap and just deactivate SSL
```
from datetime import datetime
from json import dumps
import logging
import os
from pylogbeat import PyLogBeatClient

logging.basicConfig(level=logging.DEBUG)
logging.getLogger('pylogbeat').setLevel(logging.DEBUG)

HOST = 'logstash-svc'
PORT = 5043
MESSAGE = {
    "@timestamp": datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S'),
    "@version": "1",
    "source": "/filebeatroot/test.perf.log",
    "host": "test-16-27djk",
    "from": "simulation",
    "message": "2020-03-25 01:02:03,300;pool-13-thread-3;key;value;ms"
}
SSL_VERIFY = False
KEYFILE = 'certificate.key'
CERTFILE = 'certificate.crt'
CA_CERTS = 'ca.crt'


def main():
    client_arguments = dict(
        host=HOST,
        port=PORT,
        ssl_enable=False,
        ssl_verify=SSL_VERIFY,
        keyfile=KEYFILE,
        certfile=CERTFILE,
        ca_certs=CA_CERTS,
        use_logging=True)

    client = PyLogBeatClient(**client_arguments)
    client.connect()

    message = MESSAGE

    # send a single message, as dictionary
    client.send([message] * 2)
    client.close()

    with PyLogBeatClient(**client_arguments) as client_2:
        # send a single message, as JSON
        json_message = dumps(message)
        client_2.send([message])

        # send multiple messages
        client_2.send([json_message, message, json_message, message])


if __name__ == '__main__':
    main()
```

**Comment by eht16** [comment]
The same code as above with Logstash 5.6.10 fails differently for me:
```DEBUG:pylogbeat:Sent window size: 2
DEBUG:pylogbeat:Sent payload bytes: 193, waiting for ACK: 2
DEBUG:pylogbeat:Received ACK: 2
DEBUG:pylogbeat:Sent window size: 1
DEBUG:pylogbeat:Sent payload bytes: 184, waiting for ACK: 1
DEBUG:pylogbeat:Received ACK: 1
DEBUG:pylogbeat:Sent window size: 4
DEBUG:pylogbeat:Sent payload bytes: 201, waiting for ACK: 5
DEBUG:pylogbeat:Received ACK: 4
```
After that it breaks about a few minutes because Logstash terminates the connection. PyLogBeat keeps reading from the socket as it expects sequence number 5 but only get 4 from Logstash.
There seems something wrong.

However, I then tested the same code against Logstash 6.7.1 and 7.6.2 (current version) and both work properly. So maybe this is also a bug or at least different protocol implementation in Logstash 5.x.
I might need to debug this further.

Used Logstash config:
```
logstash-7.6.2/bin/logstash --log.level=debug -e '
input {
	beats {
		port => 5043
	}
}
output {
	file {
		path => "/tmp/ls_output7"
	}
}'
```

Can you post your Logstash configuration pleasse?
I'm wondering why it fails for me differently than for you.

**Comment by eht16** [comment]
See:
https://www.elastic.co/guide/en/logstash/6.7/logstash-6-4-0.html
https://www.elastic.co/guide/en/logstash/5.6/logstash-5-6-12.html

In those both releases, a fix (https://github.com/logstash-plugins/logstash-input-beats/pull/342) in the sequence number handling in the Beats input is mentioned which explains my results (Logstash sends sequence 4 but 5 is expected).

So, ideally updating your Logstash version solves the problem.
Even though I'm still puzzled why your failure is so different.

**Comment by eht16** [comment]
Just tested with Logstash 5.6.16: works for me.
